# Site settings
title: My Blooming Life
header-img: img/home-bg.png
email: peytondflowers@gmail.com
copyright_name: PEYTONDFLOWERS
description: > # this means to ignore newlines until "baseurl:"
  A look at growth
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  PEYTONDFLOWERS
learn_profile: PEYTONDFLOWERS
email_username: peytondflowers@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
